---
version: 2
multicolumn: false
web-width: 500
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/d3js/d3js.html
    type: html
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/8850/articles/203647/master/file/figures/d3js/d3js.html"
    folder_url: "/users/8850/articles/203647/master/folder/figures/d3js"
